import { DataSource } from 'typeorm';
import { Employee } from '../../modules/organization/entities/employee.entity';

export async function seedEmployees(dataSource: DataSource) {
  const repo = dataSource.getRepository(Employee);

  const existing = await repo.count();
  if (existing > 0) {
    console.log('[Seed] Employees already seeded, skipping...');
    return;
  }

  const employees: Partial<Employee>[] = [
    {
      employeeCode: 'EMP-001',
      firstName: 'Sarah',
      lastName: 'Jenkins',
      email: 'sarah.j@acme.com',
      phone: '+91 98765 43210',
      designation: 'VP of Operations',
      departmentName: 'Operations',
      employmentStatus: 'Active',
      employmentType: 'Permanent',
      gender: 'Female',
      dateOfJoining: '2018-03-15',
      dateOfBirth: '1985-07-22',
    },
    {
      employeeCode: 'EMP-002',
      firstName: 'Rahul',
      lastName: 'Sharma',
      email: 'rahul.s@acme.com',
      phone: '+91 98765 43211',
      designation: 'Senior Scientist',
      departmentName: 'Formulation R&D',
      employmentStatus: 'Active',
      employmentType: 'Permanent',
      gender: 'Male',
      dateOfJoining: '2019-06-01',
      dateOfBirth: '1990-11-08',
    },
    {
      employeeCode: 'EMP-003',
      firstName: 'Priya',
      lastName: 'Patel',
      email: 'priya.p@acme.com',
      phone: '+91 98765 43212',
      designation: 'HR Manager',
      departmentName: 'Human Resources',
      employmentStatus: 'On Leave',
      employmentType: 'Permanent',
      gender: 'Female',
      dateOfJoining: '2017-01-10',
      dateOfBirth: '1988-04-14',
    },
    {
      employeeCode: 'EMP-004',
      firstName: 'Amit',
      lastName: 'Kumar',
      email: 'amit.k@acme.com',
      phone: '+91 98765 43213',
      designation: 'Machine Operator',
      departmentName: 'Production Core',
      employmentStatus: 'Active',
      employmentType: 'Permanent',
      gender: 'Male',
      dateOfJoining: '2020-09-20',
      dateOfBirth: '1992-02-28',
    },
    {
      employeeCode: 'EMP-005',
      firstName: 'Rajesh',
      lastName: 'Iyer',
      email: 'rajesh.i@acme.com',
      phone: '+91 98765 43214',
      designation: 'QC Lead',
      departmentName: 'Quality Control',
      employmentStatus: 'Active',
      employmentType: 'Permanent',
      gender: 'Male',
      dateOfJoining: '2016-11-05',
      dateOfBirth: '1984-09-30',
    },
    {
      employeeCode: 'EMP-006',
      firstName: 'Neha',
      lastName: 'Gupta',
      email: 'neha.g@acme.com',
      phone: '+91 98765 43215',
      designation: 'Regulatory Affairs Officer',
      departmentName: 'Regulatory Affairs',
      employmentStatus: 'Active',
      employmentType: 'Permanent',
      gender: 'Female',
      dateOfJoining: '2021-02-14',
      dateOfBirth: '1993-06-18',
    },
    {
      employeeCode: 'EMP-007',
      firstName: 'Vikram',
      lastName: 'Singh',
      email: 'vikram.s@acme.com',
      phone: '+91 98765 43216',
      designation: 'Plant Manager',
      departmentName: 'Production Core',
      employmentStatus: 'Active',
      employmentType: 'Permanent',
      gender: 'Male',
      dateOfJoining: '2015-08-01',
      dateOfBirth: '1980-12-05',
    },
    {
      employeeCode: 'EMP-008',
      firstName: 'Ananya',
      lastName: 'Deshmukh',
      email: 'ananya.d@acme.com',
      phone: '+91 98765 43217',
      designation: 'Finance Analyst',
      departmentName: 'Finance & Accounts',
      employmentStatus: 'Probation',
      employmentType: 'Permanent',
      gender: 'Female',
      dateOfJoining: '2024-01-08',
      dateOfBirth: '1996-03-25',
    },
    {
      employeeCode: 'EMP-009',
      firstName: 'Karan',
      lastName: 'Mehta',
      email: 'karan.m@acme.com',
      phone: '+91 98765 43218',
      designation: 'IT Support Engineer',
      departmentName: 'Information Technology',
      employmentStatus: 'Active',
      employmentType: 'Contract',
      gender: 'Male',
      dateOfJoining: '2022-07-11',
      dateOfBirth: '1994-10-02',
    },
    {
      employeeCode: 'EMP-010',
      firstName: 'Deepika',
      lastName: 'Nair',
      email: 'deepika.n@acme.com',
      phone: '+91 98765 43219',
      designation: 'Warehouse Supervisor',
      departmentName: 'Warehouse & Logistics',
      employmentStatus: 'Active',
      employmentType: 'Permanent',
      gender: 'Female',
      dateOfJoining: '2019-04-22',
      dateOfBirth: '1991-01-15',
    },
  ];

  await repo.save(employees.map(e => repo.create(e)));
  console.log(`[Seed] ${employees.length} dummy employees created`);
}
